<script setup lang="ts">
definePageMeta({ layout: 'public' })
type Collection<T> = { data: T[] }
type Meta = { title: string; description: string; hero_eyebrow: string; hero_headline: string; hero_subheadline: string; hero_image?: string }
const { data: meta } = await useAsyncData('public-meta-home', () => $fetch<{ data: Meta }>('/api/public/meta?route=/'))
const { data: settings } = await useAsyncData('public-home-settings', () => $fetch<{ data: Record<string, any> }>('/api/public/settings'))
const { data: stats } = await useAsyncData('public-stats-home', () => $fetch<Collection<any>>('/api/public/stats?section=hero'))
const { data: services } = await useAsyncData('public-services-home', () => $fetch<Collection<any>>('/api/public/services'))
const { data: properties } = await useAsyncData('public-properties-home', () => $fetch<Collection<any>>('/api/public/properties?featured=1&per_page=4'))
const { data: values } = await useAsyncData('public-values-home', () => $fetch<Collection<any>>('/api/public/values'))
const { data: testimonials } = await useAsyncData('public-testimonials-home', () => $fetch<Collection<any>>('/api/public/testimonials'))
useSeoMeta({ title: () => meta.value?.data.title, description: () => meta.value?.data.description })
</script>

<template>
  <section class="relative overflow-hidden bg-emerald-950 px-5 py-28 text-white sm:px-8"><img v-if="meta?.data.hero_image" :src="meta.data.hero_image" alt="" class="absolute inset-0 h-full w-full object-cover opacity-35"><div class="relative mx-auto max-w-7xl"><p class="text-sm uppercase tracking-[.2em] text-emerald-200">{{ meta?.data.hero_eyebrow }}</p><h1 class="mt-5 max-w-4xl text-5xl font-semibold tracking-tight sm:text-7xl">{{ meta?.data.hero_headline }}</h1><p class="mt-6 max-w-xl text-lg text-emerald-100/80">{{ meta?.data.hero_subheadline }}</p><NuxtLink v-if="settings?.data.home_hero_cta_label && settings?.data.home_hero_cta_url" :to="settings.data.home_hero_cta_url" class="mt-9 inline-flex rounded-full bg-white px-6 py-3.5 text-sm font-medium text-emerald-950">{{ settings.data.home_hero_cta_label }}</NuxtLink><dl class="mt-14 grid max-w-3xl grid-cols-2 gap-8 border-t border-white/20 pt-8 md:grid-cols-4"><div v-for="stat in stats?.data" :key="stat.id"><dt class="text-3xl">{{ stat.value }}</dt><dd class="mt-1 text-xs uppercase tracking-widest text-white/60">{{ stat.label }}</dd></div></dl></div></section>
  <PublicContentBlocks :blocks="meta?.data?.blocks" />
  <section class="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div class="grid gap-6 md:grid-cols-3"><article v-for="service in services?.data" :key="service.id" class="rounded-2xl border border-stone-200 bg-white p-7"><h2 class="text-2xl">{{ service.title }}</h2><p class="mt-3 text-sm leading-6 text-stone-500">{{ service.short_description }}</p><ul class="mt-5 space-y-2 text-sm"><li v-for="item in service.items" :key="item.id">{{ item.text }}</li></ul></article></div></section>
  <section v-if="properties?.data?.length" class="bg-stone-100/70 px-5 py-20 sm:px-8"><div class="mx-auto max-w-7xl"><div class="grid gap-7 md:grid-cols-2 lg:grid-cols-4"><article v-for="property in properties.data" :key="property.id" class="overflow-hidden rounded-2xl border border-stone-200 bg-white"><img v-if="property.hero_image" :src="property.hero_image" :alt="property.title" class="aspect-[4/3] w-full object-cover"><div class="p-5"><h2 class="text-xl">{{ property.title }}</h2><p class="mt-2 text-sm text-stone-500">{{ property.location }}</p><p class="mt-4 text-sm font-medium">{{ property.price_label }}</p></div></article></div></div></section>
  <NuxtLink v-if="settings?.data.home_content?.new_listing" to="/properties" class="mx-auto flex max-w-7xl items-center gap-6 px-5 py-8 sm:px-8"><img :src="settings.data.home_content.new_listing.image" :alt="settings.data.home_content.new_listing.title" class="h-24 w-32 rounded-xl object-cover"><div><p class="text-xs uppercase tracking-[.2em] text-emerald-700">{{ settings.data.home_content.new_listing.eyebrow }}</p><h2 class="mt-1 text-xl text-emerald-950">{{ settings.data.home_content.new_listing.title }}</h2><p class="mt-1 text-sm text-stone-500">{{ settings.data.home_content.new_listing.summary }}</p></div></NuxtLink>
  <section v-if="settings?.data.home_content?.about" class="mx-auto max-w-7xl px-5 py-20 sm:px-8"><p class="text-sm uppercase tracking-[.2em] text-emerald-700">{{ settings.data.home_content.about.eyebrow }}</p><h2 class="mt-3 max-w-xl text-4xl font-semibold text-emerald-950">{{ settings.data.home_content.about.headline }}</h2><p class="mt-5 max-w-2xl leading-7 text-stone-600">{{ settings.data.home_content.about.body }}</p></section>
  <section v-if="settings?.data.home_content?.sustainability" class="bg-emerald-900 px-5 py-20 text-white sm:px-8"><div class="mx-auto max-w-7xl"><p class="text-sm uppercase tracking-[.2em] text-emerald-200">{{ settings.data.home_content.sustainability.eyebrow }}</p><h2 class="mt-3 max-w-2xl text-4xl font-semibold">{{ settings.data.home_content.sustainability.headline }}</h2><p class="mt-5 max-w-2xl leading-7 text-emerald-100/80">{{ settings.data.home_content.sustainability.body }}</p></div></section>
  <section v-if="settings?.data.home_content?.airbnb" class="mx-auto max-w-7xl px-5 py-20 sm:px-8"><p class="text-sm uppercase tracking-[.2em] text-emerald-700">{{ settings.data.home_content.airbnb.eyebrow }}</p><h2 class="mt-3 text-4xl font-semibold text-emerald-950">{{ settings.data.home_content.airbnb.headline }}</h2><p class="mt-5 max-w-2xl leading-7 text-stone-600">{{ settings.data.home_content.airbnb.body }}</p></section>
  <section v-if="values?.data?.length" class="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div class="grid gap-6 md:grid-cols-2 lg:grid-cols-4"><article v-for="value in values.data" :key="value.id" class="border-t border-stone-300 pt-4"><h2 class="font-medium">{{ value.title }}</h2><p class="mt-2 text-sm leading-6 text-stone-500">{{ value.description }}</p></article></div></section>
  <section v-if="testimonials?.data?.length" class="bg-emerald-50 px-5 py-20 sm:px-8"><div class="mx-auto grid max-w-7xl gap-6 md:grid-cols-3"><figure v-for="testimonial in testimonials.data" :key="testimonial.id" class="rounded-2xl border border-stone-200 bg-white p-7"><blockquote class="leading-7 text-stone-700">“{{ testimonial.quote }}”</blockquote><figcaption class="mt-6 border-t border-stone-200 pt-5 text-sm"><strong>{{ testimonial.author_name }}</strong><p class="text-stone-500">{{ testimonial.author_role }}</p></figcaption></figure></div></section>
  <section v-if="settings?.data.home_content?.why" class="mx-auto max-w-7xl px-5 py-20 sm:px-8"><p class="text-sm uppercase tracking-[.2em] text-emerald-700">{{ settings.data.home_content.why.eyebrow }}</p><h2 class="mt-3 text-4xl font-semibold text-emerald-950">{{ settings.data.home_content.why.headline }}</h2><div class="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><article v-for="item in settings.data.home_content.why.items" :key="item.title" class="rounded-2xl border border-stone-200 bg-white p-6"><h3 class="text-xl text-emerald-950">{{ item.title }}</h3><p class="mt-2 text-sm leading-6 text-stone-500">{{ item.description }}</p></article></div></section>
  <section class="relative px-5 py-20 sm:px-8" :style="settings?.data.home_background_image ? { backgroundImage: `linear-gradient(rgba(251,250,245,.92), rgba(251,250,245,.95)), url(${settings.data.home_background_image})`, backgroundSize: 'cover' } : undefined"><div class="relative mx-auto max-w-5xl text-center"><p class="text-sm uppercase tracking-[.2em] text-emerald-700">{{ meta?.data.hero_eyebrow }}</p><h2 class="mt-3 text-4xl font-semibold text-emerald-950 sm:text-6xl">{{ meta?.data.hero_headline }}</h2><NuxtLink v-if="settings?.data.home_footer_cta_label && settings?.data.home_footer_cta_url" :to="settings.data.home_footer_cta_url" class="mt-8 inline-flex rounded-full bg-emerald-900 px-6 py-3.5 text-sm font-medium text-white">{{ settings.data.home_footer_cta_label }}</NuxtLink></div></section>
</template>
