<script setup lang="ts">
definePageMeta({ layout: 'dashboard', middleware: ['auth'] })
const route = useRoute()
const router = useRouter()
const search = ref('')
const page = ref(Number(route.query.page || 1))
const query = computed(() => `/api/admin/media?per_page=48&page=${page.value}${search.value.trim() ? `&search=${encodeURIComponent(search.value.trim())}` : ''}`)
const { data, refresh, error } = await useFetch<{ data: any[]; meta: any }>(() => query.value, { watch: [query] })
const { data: profile } = await useFetch<{ data: { role: string } }>('/api/auth/me', { key: 'dashboard-user', server: false })
const file = ref<File>(); const alt = ref(''); const pending = ref(false); const problem = ref('')
const canDelete = computed(() => profile.value?.data.role === 'admin')
watch(search, () => { page.value = 1; router.replace({ query: { ...route.query, search: search.value || undefined, page: undefined } }) })
watch(() => route.query.page, value => { page.value = Number(value || 1) })
function choose(event: Event) { file.value = (event.target as HTMLInputElement).files?.[0] }
async function upload() { if (!file.value) return; pending.value = true; problem.value = ''; const body = new FormData(); body.append('file', file.value); body.append('alt', alt.value); try { await $fetch('/api/admin/media/upload', { method: 'POST', body }); file.value = undefined; alt.value = ''; await refresh() } catch (requestError: any) { problem.value = requestError?.data?.message || 'Upload failed.' } finally { pending.value = false } }
async function remove(id: number) { if (!canDelete.value || !confirm('Delete this media file?')) return; try { await $fetch(`/api/admin/media/${id}`, { method: 'DELETE' }); await refresh() } catch (requestError: any) { problem.value = requestError?.data?.message || 'Delete failed.' } }
</script>
<template><section class="space-y-6"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-emerald-800">Library</p><h2 class="mt-2 text-2xl font-semibold">Media</h2><p class="mt-1 text-sm text-slate-500">{{ data?.meta?.total ?? 0 }} assets</p></div><form class="flex flex-wrap items-center gap-2" @submit.prevent="upload"><input type="file" accept="image/*" @change="choose"><input v-model="alt" placeholder="Alt text" class="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><button :disabled="pending" class="rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{{ pending ? 'Uploading…' : 'Upload' }}</button></form></div><Alert v-if="error" variant="error" :message="(error as any).data?.message || 'Unable to load media.'" /><Alert v-if="problem" variant="error" :message="problem" /><input v-model="search" type="search" placeholder="Search alt text or filename" class="w-full max-w-lg rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><LoadingSkeleton v-if="!data && !error" /><div v-else class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4"><article v-for="item in data?.data" :key="item.id" class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><img :src="item.url" :alt="item.alt || ''" class="aspect-[4/3] w-full object-cover"><div class="flex items-center justify-between gap-2 p-3 text-xs"><span class="truncate text-slate-600">{{ item.alt || item.path }}</span><button v-if="canDelete" class="shrink-0 text-rose-700" @click="remove(item.id)">Delete</button></div></article></div><EmptyState v-if="data && !data.data.length" title="No matching media" description="Upload an asset or change your search." /><Pagination v-if="data?.meta" :current-page="data.meta.current_page" :last-page="data.meta.last_page" @change="(nextPage) => router.push({ query: { ...route.query, page: String(nextPage) } })" /></section></template>